// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package br.com.robsonmrsp.proto;

public interface HelloWorldMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.HelloWorldMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   * @return The greeting.
   */
  java.lang.String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   * @return The bytes for greeting.
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
